[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring"]

[phases.build]
cmds = ["echo 'PHP project - no build required'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."